version: "3"
services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:12
    expose:
      - "5432"
  notebooks:
    build: .
    volumes:
      - ./src:/home/jovyan/
      - ./data:/home/jovyan/datasets
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_ADDRESS: db
      POSTGRES_PORT: 5432
    ports:
      - 8888:8888
    links:
      - db:db
    depends_on:
      - "db"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
